name: Python Package CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest tests/

      - name: Build and Publish Package
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          python setup.py sdist bdist_wheel
          python -m pip install twine
          twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: Build .exe File
        if: matrix.python-version == '3.9'
        timeout-minutes: 10
        run: |
          python -m pip install pyinstaller
          pyinstaller --onefile --name OptiFlowPy --noconsole --icon=assets/icon.png src/main.py

      - name: Create Release
        if: matrix.python-version == '3.9' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
